### ISSUE TITLE
Bulbs are not identified

### ISSUE THREAD

**Issue by Mobidick1112** [nischcodes/homebridge-wiz-net#1]
Wiz bulbs are not identified, when with the version "Wiz Lan" from "kpsuperplane" they are. The plugs ESP25 are well identified with your version, but that is not the cas for version "Wiz Lan". A mix of both would be great, but I don't know how to do it.

**Comment by nischcodes** [comment]
Sorry @Mobidick1112 for your inconveniences. This project isn‘t a real fork of the „kpsuperplane“ version, so there is no back porting of any modifications by me. This project was a weekend hack without any intentions to really work on this project actively. 

If you only want to use my version in conjunction to the „kpsuperplane“ version comment out the hole line 3 of the file /accessories/index.ts and delete the „socket“ variable in line 6 of the same file. Than my code only supports the „ESP_25“ sockets. 

Oh and don’t forget to change the default port in the configurations. Both plugins uses the same port for communication. And so you have to make sure that both have a dedicated port.

Hope that helps you a bit.

**Comment by Mobidick1112** [comment]
Tanks for quick response. The idea to modify the file is a good idea, but I’m not able to save the new version of the file.

Regards

**Comment by nischcodes** [comment]
If you have modified the files on you computer, you have to run the build command specified in the package.json because node can’t run typescript files. In order to run the build command you must have node.js installed and also the development dependencies (use the npm -i command). This will install esbuild and all the other libraries. After you have successfully run the build command you can replace the js file in the dist folder of your homebridge plugin.

if you have trouble or you are new to this kind of development, with your request I had the idea to add configuration fields for plug und socket, so that you can enable and disable them without any modifications on my code. Today I am busy with some other projects, but I am planing to add this new feature next week. If you want to wait.

Another open Task is an update of the plug-in in general, because the current implementation isn’t best practice recommended by the homebridge project.

**Comment by Mobidick1112** [comment]
Thanks for your help, but it becomes to complex for me. I prefer wait a new version when you have time to do it. Don’t worry it’s already very interesting to have this kind of discussion, that just show nothing is very easy.

Nice day

Dominique

**Comment by Mobidick1112** [comment]
Hello,

The problem was finally solved by the owner of the original plugin.

Thanks for your help and nice day

Dominique
